from __future__ import annotations

STRINGS = {
    "zh": {
        "app_title": "回收站清理工具",
        "ready": "就绪",
        "scanning": "扫描中...",
        "scan_failed": "扫描失败",
        "cancelled": "已取消",
        "cleaning": "清理中...",
        "by_ext": "  按文件类型  ",
        "by_path": "  按原始路径  ",
        "by_folder": "  按文件夹名  ",
        "by_date": "  按删除日期  ",
        "by_size": "  按文件大小  ",
        "ext_label": "输入扩展名，多个用空格或逗号分隔：",
        "ext_hint": "示例:  .tmp  .log  .cache  .ps1  .pyc  .class",
        "path_label": "输入文件的原始父文件夹路径：",
        "browse": "浏览…",
        "path_hint": "示例:  C:\\Users\\xxx\\AppData\\Local\\Temp",
        "folder_label": "输入文件夹名，删除该文件夹下所有文件：",
        "folder_hint": "示例:  json  则会匹配 F:\\a\\json\\1.txt 和 C:\\Projects\\json\\data.json",
        "date_label": "选择删除日期范围（留空表示不限）：",
        "from": "从:",
        "to": "到:",
        "date_hint": "格式: 2025-01-01  或  2025-01-01 12:30",
        "size_label": "选择文件大小范围（留空表示不限）：",
        "size_hint": "示例:  10MB  或  1.5GB  或  500KB",
        "size_from": "最小:",
        "size_to": "最大:",
        "start_clean": "开始清理",
        "exec_log": "执行日志",
        "log_path": "日志路径: ",
        "export_csv": "导出CSV",
        "open_log_dir": "打开日志目录",
        "lang_switch": "EN",
        "prompt_ext": "请输入至少一个文件扩展名",
        "prompt_ext_fmt": "扩展名格式不正确",
        "prompt_path": "请输入原始文件夹路径",
        "prompt_folder": "请输入文件夹名称",
        "prompt_date_fmt_s": "起始日期格式不正确，请使用 YYYY-MM-DD",
        "prompt_date_fmt_e": "结束日期格式不正确，请使用 YYYY-MM-DD",
        "prompt_date_at_least": "请至少输入一个日期",
        "prompt_size": "请至少输入一个大小值",
        "prompt_size_fmt": "大小格式不正确，示例: 100MB、1.5GB、500KB",
        "mode_size": "清理模式: 按文件大小",
        "mode_ext": "清理模式: 按文件类型",
        "mode_path": "清理模式: 按原始路径",
        "mode_folder": "清理模式: 按文件夹名",
        "mode_date": "清理模式: 按删除日期",
        "target_ext": "目标扩展名: ",
        "target_path": "目标路径: ",
        "target_folder": "目标文件夹: ",
        "target_size": "目标大小: ",
        "date_range": "日期范围: ",
        "date_from_only": "删除日期 >= ",
        "date_to_only": "删除日期 <= ",
        "skipped_no_date": "（{n} 个无删除日期信息的项目已跳过）",
        "no_match": "没有匹配的文件需要清理。",
        "found_n": "\n找到 {n} 个匹配文件，共 {sz}",
        "confirm_delete": "确认删除",
        "confirm_msg": "即将删除 {n} 个文件，释放 {sz} 空间。\n\n确认继续？",
        "user_cancel": "用户取消操作。",
        "clean_done": "清理完成!",
        "deleted": "  删除: ",
        "freed": "  释放: ",
        "failed": "  失败: ",
        "failed_reason": "（可能被占用）",
        "delete_item": "  删除: ",
        "no_folder_match": "没有找到路径中包含文件夹 [{name}] 的文件",
        "scan_err_ps": "[错误] PowerShell 执行失败: ",
        "scan_err_empty": "[错误] 回收站扫描结果为空",
        "scan_done": "扫描完成，共 {n} 个项目",
        "scan_skip": "[提示] {n} 个条目格式异常已跳过",
        "scan_timeout": "[错误] 扫描超时（超过60秒）",
        "scan_exception": "[错误] 扫描异常: ",
        "done_status": "完成 — 删除 {n} 个，释放 {sz}",
        "guide_title": "使用说明",
        "guide_text": (
            "欢迎使用回收站清理工具！\n\n"
            "功能说明：\n"
            "1. 按文件类型：根据扩展名筛选回收站文件\n"
            "2. 按原始路径：删除来自指定目录的文件\n"
            "3. 按文件夹名：删除属于特定文件夹的文件\n"
            "4. 按删除日期：按删除时间范围清理\n"
            "5. 按文件大小：按文件大小筛选清理\n\n"
            "注意事项：\n"
            "- 删除操作不可恢复，请谨慎操作\n"
            "- 建议先预览结果再确认删除\n"
            "- 如遇问题请查看日志文件"
        ),
        "guide_confirm": "我已了解，不再显示",
        "guide_ok": "确定",
        "preview_title": "预览结果",
        "preview_msg": "命中 {n} 个文件，总大小 {sz}\n\n示例条目（最多5个）：\n{samples}\n\n是否继续执行删除？",
        "preview_confirm": "确认删除",
        "preview_cancel": "取消",
        "export_title": "导出CSV",
        "export_success": "已导出到: {path}",
        "export_empty": "没有可导出的数据",
        "update_title": "发现新版本",
        "update_msg": "当前版本: v{cur}\n最新版本: v{new}\n\n是否前往下载页面？",
        "update_yes": "前往下载",
        "update_no": "稍后再说",
        "update_checking": "正在检查更新...",
        "update_latest": "已是最新版本",
        "update_err": "更新检查失败",
        "selfcheck_title": "自检",
        "selfcheck_pass": "自检通过",
        "selfcheck_fail": "自检失败",
        "selfcheck_detail": "启动自检发现问题：\n\n{detail}\n\n是否继续启动？",
        "selfcheck_continue": "继续启动",
        "selfcheck_quit": "退出",
        "err_title": "错误",
        "err_msg": "操作过程中发生错误：\n\n{err}\n\n详细信息已记录到日志文件。",
        "err_copy": "复制错误信息",
        "close": "关闭",
    },
    "en": {
        "app_title": "Recycle Bin Cleaner",
        "ready": "Ready",
        "scanning": "Scanning...",
        "scan_failed": "Scan failed",
        "cancelled": "Cancelled",
        "cleaning": "Cleaning...",
        "by_ext": "  By File Type  ",
        "by_path": "  By Original Path  ",
        "by_folder": "  By Folder Name  ",
        "by_date": "  By Delete Date  ",
        "by_size": "  By File Size  ",
        "ext_label": "Enter extensions, separated by space or comma:",
        "ext_hint": "Example:  .tmp  .log  .cache  .ps1  .pyc  .class",
        "path_label": "Enter the original parent folder path:",
        "browse": "Browse...",
        "path_hint": "Example:  C:\\Users\\xxx\\AppData\\Local\\Temp",
        "folder_label": "Enter folder name to delete all files under it:",
        "folder_hint": "Example:  json  matches F:\\a\\json\\1.txt and C:\\Projects\\json\\data.json",
        "date_label": "Select delete date range (leave empty for no limit):",
        "from": "From:",
        "to": "To:",
        "date_hint": "Format: 2025-01-01  or  2025-01-01 12:30",
        "size_label": "Select file size range (leave empty for no limit):",
        "size_hint": "Example:  10MB  or  1.5GB  or  500KB",
        "size_from": "Min:",
        "size_to": "Max:",
        "start_clean": "Start Cleaning",
        "exec_log": "Execution Log",
        "log_path": "Log: ",
        "export_csv": "Export CSV",
        "open_log_dir": "Open Log Folder",
        "lang_switch": "中",
        "prompt_ext": "Please enter at least one file extension",
        "prompt_ext_fmt": "Extension format is incorrect",
        "prompt_path": "Please enter the original folder path",
        "prompt_folder": "Please enter a folder name",
        "prompt_date_fmt_s": "Start date format is incorrect, use YYYY-MM-DD",
        "prompt_date_fmt_e": "End date format is incorrect, use YYYY-MM-DD",
        "prompt_date_at_least": "Please enter at least one date",
        "prompt_size": "Please enter at least one size value",
        "prompt_size_fmt": "Size format is incorrect, example: 100MB, 1.5GB, 500KB",
        "mode_size": "Mode: By File Size",
        "mode_ext": "Mode: By File Type",
        "mode_path": "Mode: By Original Path",
        "mode_folder": "Mode: By Folder Name",
        "mode_date": "Mode: By Delete Date",
        "target_ext": "Target extensions: ",
        "target_path": "Target path: ",
        "target_folder": "Target folder: ",
        "target_size": "Target size: ",
        "date_range": "Date range: ",
        "date_from_only": "Delete date >= ",
        "date_to_only": "Delete date <= ",
        "skipped_no_date": "({n} items without date info skipped)",
        "no_match": "No matching files to clean.",
        "found_n": "\nFound {n} matching files, total {sz}",
        "confirm_delete": "Confirm Delete",
        "confirm_msg": "About to delete {n} files, freeing {sz}.\n\nConfirm?",
        "user_cancel": "Cancelled by user.",
        "clean_done": "Cleaning complete!",
        "deleted": "  Deleted: ",
        "freed": "  Freed: ",
        "failed": "  Failed: ",
        "failed_reason": " (may be in use)",
        "delete_item": "  Deleted: ",
        "no_folder_match": "No files found with folder [{name}] in path",
        "scan_err_ps": "[Error] PowerShell failed: ",
        "scan_err_empty": "[Error] Recycle bin scan result is empty",
        "scan_done": "Scan complete, {n} items found",
        "scan_skip": "[Info] {n} malformed entries skipped",
        "scan_timeout": "[Error] Scan timed out (60s)",
        "scan_exception": "[Error] Scan exception: ",
        "done_status": "Done - Deleted {n}, freed {sz}",
        "guide_title": "Usage Guide",
        "guide_text": (
            "Welcome to Recycle Bin Cleaner!\n\n"
            "Features:\n"
            "1. By File Type: Filter recycle bin files by extension\n"
            "2. By Original Path: Delete files from a specific directory\n"
            "3. By Folder Name: Delete files belonging to a folder\n"
            "4. By Delete Date: Clean by delete time range\n"
            "5. By File Size: Clean by file size\n\n"
            "Notes:\n"
            "- Deletion is irreversible, please be careful\n"
            "- Preview results before confirming deletion\n"
            "- Check the log file if you encounter issues"
        ),
        "guide_confirm": "Got it, don't show again",
        "guide_ok": "OK",
        "preview_title": "Preview Results",
        "preview_msg": "Matched {n} files, total {sz}\n\nSample entries (up to 5):\n{samples}\n\nProceed with deletion?",
        "preview_confirm": "Confirm Delete",
        "preview_cancel": "Cancel",
        "export_title": "Export CSV",
        "export_success": "Exported to: {path}",
        "export_empty": "No data to export",
        "update_title": "New Version Available",
        "update_msg": "Current: v{cur}\nLatest: v{new}\n\nGo to download page?",
        "update_yes": "Download",
        "update_no": "Later",
        "update_checking": "Checking for updates...",
        "update_latest": "Already up to date",
        "update_err": "Update check failed",
        "selfcheck_title": "Self-Check",
        "selfcheck_pass": "Self-check passed",
        "selfcheck_fail": "Self-check failed",
        "selfcheck_detail": "Startup self-check found issues:\n\n{detail}\n\nContinue anyway?",
        "selfcheck_continue": "Continue",
        "selfcheck_quit": "Quit",
        "err_title": "Error",
        "err_msg": "An error occurred:\n\n{err}\n\nDetails have been logged.",
        "err_copy": "Copy Error",
        "close": "Close",
    },
}
